# Generated by Django 3.2.9 on 2022-04-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=False, upload_to='category_images/'),
        ),
    ]
