# Generated by Django 3.2.9 on 2022-04-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main', '0004_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=False, upload_to='products_images/', verbose_name='Изображение'),
        ),
    ]
