# Generated by Django 3.2.9 on 2022-04-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main', '0005_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category_images/', verbose_name='Изображение'),
        ),
    ]
