# Generated by Django 3.2.9 on 2022-06-25 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main', '0007_auto_20220408_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Характеристика')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание характеристики')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop_main.category', verbose_name='Категория')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop_main.categoryproperty', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryPropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_main.product', verbose_name='Товар')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_main.categoryproperty', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Значение',
                'verbose_name_plural': 'Значения характеристик',
                'ordering': ['product'],
            },
        ),
    ]
