# Generated by Django 3.2.9 on 2022-06-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main', '0008_categoryproperty_categorypropertyvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='product',
            name='time_update',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=0, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
